#!/usr/bin/env bash

if [ "$1" == "start" ]; then
    docker-compose start
fi

if [ "$1" == "stop" ]; then
    docker-compose stop
fi

if [ "$1" == "update" ]; then
    docker-compose down
    docker-compose pull && docker-compose up -d
fi

if [ "$1" == "setup" ]; then
  echo 'Setting system...' \
  && sudo apt upgrade -y \
  && rm -rf ghost; git clone https://github.com/woosungchoi/ghost-cms ghost \
  && cd ghost \
  && sed -e "s/<domain>/$2/g" docker-compose.yml \
  && sed -e "s/<email>/$3/g" docker-compose.yml \
  && sed -e "s/<domain>/$2/g" nginx/default.conf \
  && sed -e "s/<domain>/$2/g" config.production.json \
  && sed -e "s/<email>/$3/g" config.production.json \
  && echo 'Installing Docker...' \
  && sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y \
  && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - \
  && sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" -y \
  && sudo apt update -y \
  && sudo apt install docker-ce docker-ce-cli containerd.io -y \
  && echo 'Installing Docker Compose...' \
  && sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose \
  && sudo chmod +x /usr/local/bin/docker-compose \
  && echo 'Installing SSL...' \
  && mkdir ./ssl; \
  && sudo docker-compose up -d \
  && echo 'Preparing docker-compose up' \
  && sudo docker-compose down -v certbot \
  && mv docker-compose.yml docker-compose.ssl.yml \
  && mv docker-compose.production.yml docker-compose.yml \
  && echo 'Preparing Ghost...' \
  && mkdir ./content; mkdir ./mysql; sudo mkdir -p /usr/share/nginx/html; \
  echo 'Configuring cron...' \
  && echo "0 23 * * * docker start certbot && docker restart nginx" >> mycron \
  && sudo crontab mycron; rm mycron \
  && echo 'Starting Docker...' \
  && sudo docker-compose up -d \
  && echo 'Done! 🎉' \
  && echo 'by Rafael Correa Gomes and Woosung Choi' \
  && echo 'Access your host: https://'; echo $2;
fi
