#!/usr/bin/env bash

if [ "$1" == "start" ]; then
    sudo docker-compose start
fi

if [ "$1" == "stop" ]; then
    sudo docker-compose stop
fi

if [ "$1" == "update" ]; then    
    sudo docker-compose pull && sudo docker-compose up -d && sudo docker image prune -f
fi

if [ "$1" == "setup" ]; then
  echo 'Setting system...' \
  && rm -rf ghost; git clone https://github.com/woosungchoi/ghost-cms ghost \
  && cd ghost \
  && sed -i "s/<domain>/$2/g" docker-compose.yml \
  && sed -i "s/<domain>/$2/g" docker-compose.production.yml \
  && sed -i "s/<email>/$3/g" docker-compose.yml \
  && sed -i "s/<email>/$3/g" config.production.json \
  && sed -i "s/<domain>/$2/g" nginx/default.conf \
  && sed -i "s/<domain>/$2/g" config.production.json \
  && echo 'Installing Docker...' \
  && sudo yum remove -y docker docker-client docker-client-latest docker-common docker-latest docker-latest-logrotate docker-logrotate docker-engine \
  && sudo dnf install -y https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm \
  && sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo \
  && sudo dnf install -y docker-ce docker-ce-cli \
  && sudo systemctl start docker && sudo systemctl enable --now docker \
  && if [ ! -f /usr/bin/docker-compose ] ; then
        echo 'Installing Docker Compose...' \
        && COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4) \
        && sudo curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose \
        && sudo chmod +x /usr/bin/docker-compose
        else echo 'Skip Installing Docker Compose'
     fi
  echo 'Installing SSL...' \
  && sudo docker-compose up \
  && echo 'Preparing docker-compose up' \
  && sudo docker-compose down -v \
  && mv docker-compose.yml docker-compose.ssl.yml \
  && mv docker-compose.production.yml docker-compose.yml \
  && echo 'Preparing Ghost...' \
  && mkdir ./content; sudo mkdir -p /usr/share/nginx/html; \
  echo 'Configuring cron...' \
  && echo "0 23 * * * docker start certbot >> /var/log/docker_cron.log 2>&1
  5 23 * * * docker exec nginx nginx -s reload >> /var/log/docker_cron.log 2>&1" >> mycron \
  && sudo crontab mycron; rm mycron \
  && sudo chmod +x dc \
  && echo 'Starting Docker db...' \
  && sudo docker-compose up -d db \
  && echo 'Waiting 10 secs for Mariadb to build databases...' \
  && sleep 10 \
  && sudo docker-compose up -d --no-deps ghost \
  && echo 'Waiting 20 secs for Ghost to install ghost files...' \
  && sleep 20 \
  && echo 'Now starting Nginx!' \
  && sudo docker-compose up -d --no-deps nginx \
  && echo 'Done! 🎉' \
  && echo 'by Rafael Correa Gomes and Woosung Choi' \
  && echo 'Access your ghost: https://'$2;
  echo 'Access your ghost admin page: https://'$2'/ghost';
fi
