#!/usr/bin/env bash

if [ "$1" == "start" ]; then
    sudo docker-compose start
fi

if [ "$1" == "stop" ]; then
    sudo docker-compose stop
fi

if [ "$1" == "update" ]; then    
        sudo docker-compose pull && sudo docker-compose up -d && sudo docker image prune -f
fi

if [ "$1" == "setup" ]; then
  echo 'Setting system...' \
  && read -p "[1/2] Enter your domain (ex : mydomain.com or localhost) : " DOMAIN
  read -p "[2/2] Which port do you want to access the web server on? (ex : 80) " WEB_PORT \
  && rm -rf ghost; git clone https://github.com/woosungchoi/ghost-cms ghost \
  && cd ghost \
  && mv docker-compose.yml docker-compose.ssl.yml \
  && mv docker-compose.local.yml docker-compose.yml \
  && sed -i "s/<port>/$WEB_PORT/g" docker-compose.yml \
  && sed -i "s/<domain>/$DOMAIN/g" docker-compose.yml \
  && echo 'Installing Docker...' \
  && sudo yum remove -y docker docker-client docker-client-latest docker-common docker-latest docker-latest-logrotate docker-logrotate docker-engine \
  && sudo dnf install -y https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm \
  && sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo \
  && sudo dnf install -y docker-ce docker-ce-cli \
  && sudo systemctl start docker && sudo systemctl enable --now docker \
  && if [ ! -f /usr/bin/docker-compose ] ; then
        echo 'Installing Docker Compose...' \
        && COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4) \
        && sudo curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose \
        && sudo chmod +x /usr/bin/docker-compose
        else echo 'Skip Installing Docker Compose'
     fi
  sudo chmod +x dc \
  && echo 'Starting Docker and db...' \
  && sudo docker-compose up -d db \
  && echo 'Waiting 10 secs for Mariadb to build databases...' \
  && sleep 10 \
  && sudo docker-compose up -d --no-deps ghost \
  && echo 'Done! 🎉' \
  && echo 'by Rafael Correa Gomes and Woosung Choi' \
  && echo 'Access your ghost: http://'$DOMAIN':'$WEB_PORT \
  && echo 'Access your ghost admin page: http://'$DOMAIN':'$WEB_PORT'/ghost';
fi
